### ISSUE TITLE
Running test problems

### ISSUE THREAD

**Issue by laurapoggio-sptools** [gflow/GFlow#16]
I managed to install GFlow under centos7.2 
I compiled PETSC and then Gflow. Make runs without errors but with warnings (I can provide them).
I am trying to run the test script. I changed PETSC directory to the same I used to compile GFlow. I also changed the path for mpiexec (not in the default PATH) and I added full path when calling gflow.x

`/usr/lib64/mpich/bin/mpiexec -n 4 /my_local_directory/gflow/GFlow-0.1.6-alpha/gflow.x \`

I now get this message:

```
Tue 13 Jun 08:35:03 BST 2017
Attempting to use an MPI routine before initializing MPICH
Attempting to use an MPI routine before initializing MPICH
Attempting to use an MPI routine before initializing MPICH
Attempting to use an MPI routine before initializing MPICH

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   EXIT CODE: 1
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================

```
I am not sure if it is a problem of MPI or a problem with GFlow. Any pointers will be very helpful.
Thanks a lot

Laura

**Comment by Pbleonard** [comment]
@laurapoggio-sptools I think it is a problem related to MPI. Can you tell me which versions of PETSC and MPI you are using?

**Comment by eduffy** [comment]
@laurapoggio-sptools Since you compiled PETSc yourself, can you tell us the what flags you used to configure it?  `gflow` calls `PetscInitialize()` which is supposed to call `MPI_Init()`.  From the error you gave us, it sounds like PETSc may not have been compiled against your MPI library (MPICH).

**Comment by laurapoggio-sptools** [comment]
I am just back in the office. Thank you for your reply I will check and be
back to you in the next couple of days.

Thanks

**Comment by laurapoggio-sptools** [comment]
Below the compile instructions I used:

`python2 ./configure  --with-mpi-dir=/usr/lib64/mpich`

PETSC version is the latest available in June from [this repository](https://bitbucket.org/petsc/petsc)

mpich was installed using yum on centos 7 and it seems to be version 3.2

I hope this clarify and apologies for the delay.

**Comment by eduffy** [comment]
Hi @laurapoggio-sptools, can you send me your `configure.log` file that PETSc generated?  On my system it's located at `/usr/local/Cellar/petsc/3.7.3/real/lib/petsc/conf/configure.log`.  My email address is eduffy at gmail.com

**Comment by eduffy** [comment]
Hi @laurapoggio-sptools , I looked that log you emailed me and contains this line:

`ERROR while running executable: Could not execute "/usr/lib64/mpich/bin/mpiexec /tmp/petsc-JSKwiV/config.libraries/conftest":`

And I don't see anything about a successful execution of `mpiexec` or `mpirun` anywhere in the log.  Have you ran anything with this installed MPICH before?

**Comment by laurapoggio-sptools** [comment]
Hi @eduffy,
No I installed it specigically for gflow. I did not get any obvious errors when installing/compiling, but I did not l look carefully enough in the log.
I will try with a different version then and see what happens.

Thanks a lot for your help.

**Comment by eduffy** [comment]
If you don't have a particular reason using MPICH, I'd go with OpenMPI.
I've generally had more luck with it.

**Comment by whositwhatnow** [comment]
@laurapoggio-sptools i'd like to touch base with you to see how you successfully got this working on CentOS 7

**Comment by laurapoggio-sptools** [comment]
I did some tests but I was not successful. I had to leave it on a side for a while as other projects were more urgent. I will give an other go later in the year. Probably March or April. Apologies for not updating the issue.

Thanks
