### ISSUE TITLE
Cells connected to four or eight neighbors?

### ISSUE THREAD

**Issue by RMarrec** [gflow/GFlow#18]
Hi. I am wondering if gflow may allow to choose between the use of four or eight neighbors to connect cells together? If not, what is the implemented choice?
Thank you. Ronan.

**Comment by Pbleonard** [comment]
@RMarrec, I do not believe we currently have an option. The default is 8 neighbors. Are you up against a problem or setup where you'd like to use 4?

Cheers,
Paul

**Comment by RMarrec** [comment]
@Pbleonard - I guess 8 neighbors is more realistic, but in some cases, considering 8 neighbors may remove the role as barriers of some elements (especially linear features). Particularly at coarser resolutions.
For instance here with roads considered at a coarser resolution:
![example](https://user-images.githubusercontent.com/27225596/28123564-44b26762-66ef-11e7-8d70-3e9a3ccf4cae.png)
In this case, I wonder if considering only 4 neighbors will not be more realistic. At least it would be interesting to compare the two connectivity outputs.

**Comment by RMarrec** [comment]
On the picture, black areas are the less resistant. It is not intuitive, sorry.

**Comment by eduffy** [comment]
As a quick resolution, you can remove these five lines that check the diagonals:  https://github.com/Pbleonard/GFlow/blob/master/gflow.c#L285-L289

**Comment by RMarrec** [comment]
@eduffy - Thank you for your answer. It is worth a try, I will do it asap and will let you know.

**Comment by RMarrec** [comment]
@eduffy - The solution you proposed works. I tested it on one single window, and the results were not highly different. It would be good to test for more landscapes and larger extents to evaluate "statistically" the interest of using 4 instead of 8 neighbors. Especially to compare the barrier effect of linear features.

**Comment by Pbleonard** [comment]
@RMarrec, given your example above, would you mind posting the 4 connection comparison? Could be useful to others with similar questions.
