### ISSUE TITLE
Running gflow on a cluster

### ISSUE THREAD

**Issue by jmsigner** [gflow/GFlow#23]
When attempting to run gflow on a cluster, I am experiencing problems when the number of cores exceeds 16. 

I am using the following script to submit a job:

```
> cat exc_1.sh 
#!/bin/sh
#BSUB -q mpi
#BSUB -n 16
#BSUB -o output_1.txt
#BSUB -e error_1.txt
#BSUB -a openmpi
#BSUB -cwd /scratch/jsigner/asciis/for_den_rs

# load modules
module load openmpi/gcc
module load gflow/0.1.7

OUTPUT_DIR=.

mpiexec -n 16 gflow.x \
	-habitat for_den_rs.asc \
	-nodes nodes \
	-node_pairs node_pairs/form_1 \
	-effective_resistance ./res/R_eff_1.csv 

```

The above works as expected, but if I increase `-n` to lets say 128 (both `#BSUB -n 128` and `mpiexc -n 128`), I get the following output:

```
 > bpeek -f
<< output from stdout >>
Mon Jan 22 23:37:29 2018 >> Effective resistance will be written to ./res/R_eff_1.csv.
Mon Jan 22 23:37:29 2018 >> (rows,cols) = (4364,4248)
Mon Jan 22 23:37:32 2018 >> Removed 0 islands (0 cells).
Mon Jan 22 23:37:32 2018 >> 980 points in nodes
Mon Jan 22 23:37:32 2018 >> Max distance: 400000.00 pixels
Mon Jan 22 23:37:32 2018 >> 979 pairs generated.  0 skipped.
Mon Jan 22 23:37:32 2018 >> Number of unknowns: 12380248

```

And nothing happens afterwards. Do I miss a `gflow` specific argument in the LSF specification?

**Comment by eduffy** [comment]
Hi @jmsigner - I noticed you don't have a memory request; if your scheduler's default limit is low you may be hitting the limit with the increase in node count (more memory needed for mpi's communication).

If that's not it, your simulation may not be big enough for 128 cores.  We used fewer than that for 10s of millions of unknowns, and it was only taking 4 seconds per iteration.  Does it hang with any number over 16?
