### ISSUE TITLE
Issue calculating pairwise interactions

### ISSUE THREAD

**Issue by famarques** [gflow/GFlow#25]
Hello,
i´m using GFlow to calculate connectivity beetwen points in europe-wide lenght. I´ve changed the execute_example.sh flags to calculate pairwise interactions beetween all nodes. I tried a lot of changes on the flags but in all GFlow stops calculating before all pairwise nodes been calculated. 
In annex the files that i´m using and the execute_example.sh file modified with my configurations.

I´m doing something wrong?

Thank you,

[GFlow_data.zip](https://github.com/gflow/GFlow/files/1758038/GFlow_data.zip)

**Comment by pbleonard** [comment]
@famarques Can you be more specific about 

> GFlow stops calculating before all pairwise nodes been calculated.

I attempted to execute your example and noticed many of the points appear to be invalid.

**Comment by famarques** [comment]
Thanks for response,
i´m trying to calculate all interactions between points like circuitscape, but the program stops and write the results before all pairs are calculated. For example in the species of those nodes i´ve points in UK that are not showed in the results.  

Yes, but It happened also before it another species that i´ve tried to calculate, and have all or almost all points valid. 


The points and resistance raster:
![resistance 1](https://user-images.githubusercontent.com/36729425/36754088-00b06cf0-1c00-11e8-84ca-17a0179081fd.PNG)

The results:
![myo_dau_cnc 1](https://user-images.githubusercontent.com/36729425/36754116-0c566d02-1c00-11e8-8a35-e850a5a42604.PNG)

**Comment by pbleonard** [comment]
If you chose not to include the `converge_at` flag then **all pairwise** will be calculated unless there are > 1 million pairs (in this case we are aware of a bug). gflow will not calculate any pairwise connection with infinite resistance or with pairs that are not constrained inside the resistance surface. Can you tell me how you're making your points text file?

**Comment by pbleonard** [comment]
Great. Can you test with a subset of your pairs?

**Comment by famarques** [comment]
I will test it, now im working in another thing, but when i have time i will try it

**Comment by pbleonard** [comment]
@eduffy fixed the bug [here](https://github.com/gflow/GFlow/commit/b2c0b426a990ebc924cd5cac1b6caf5372ce12c0) (should already be included in release v. 0.1.7):
